### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by e-rk** [JayTheYggdrasil/ApexParkour#3]
Thanks for making and sharing this map. I think it has the potential to grow into something big for people who want to train movement.  Would it be possible to add a license for the project to clarify what other people can do with it? It's also very important if you plan on accepting contributions from other people. 

There is a guide that briefly explains the most commonly used open-source licenses: https://choosealicense.com/

**Comment by JayTheYggdrasil** [comment]
True, good call, I'll look into it. Thanks!
