### ISSUE TITLE
Is not working.

### ISSUE THREAD

**Issue by H00dedM4n** [JayTheYggdrasil/ApexParkour#4]
despite my best efforts, the script will not work. I have tried the one provided on the home page with the instructions and then the new one, but they both do not work. either it takes a while to load and then says 'Connection to server timed out and booted me out to the home screen. Or it loads with no map. I have made sure that everything is up to the latest date and that all my content is there. If I missd a step, please let me know as I am eager to try out this clever map.

**Comment by JayTheYggdrasil** [comment]
If you have it where it says the connection timed out, look in the console. There should be some kind of error reported there. Just let me know what it says, make sure to include the entire error.

**Comment by H00dedM4n** [comment]
After it kicks me out it says: Connection to server timed out {code:net} See ea.com/unable-to-connect for additional information.

**Comment by Salvodif** [comment]
I've an issue too.
The map has been copied and I created the server as is written on description but the server doesn't start

**Comment by H00dedM4n** [comment]
Ya we have the same problem

**Comment by JayTheYggdrasil** [comment]
Yep, so when it kicks you out and shows the code net, open the console by pressing ~ or insert. There should be some red text that describes some kind of error. That's what I need to know in order to fix it.

**Comment by H00dedM4n** [comment]
Oh, my bad, sorry I was a little confused there. this is the red text once I press ~ [54.105] Native(S):SERVER SCRIPT COMPILE ERROR: Undefined variable "DesertlandsTrain_Precaches"
[54.105] Native(S): -> DesertlandsTrain_Precaches()

[54.105] Native(S):mp/levels/mp_rr_desertlands_common.nut line [18] column [27]

**Comment by JayTheYggdrasil** [comment]
That's weird, that variable doesn't appear to be used anywhere in the scripts anymore. So, I think that means something with your scripts must be outdated then. How are you updating them?

**Comment by H00dedM4n** [comment]
I make sure that I download the latest possible release for the scripts if it is outdated I would just install the new version.
